### ISSUE TITLE
React Fetch Medium post

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee.design#1]
I would like to use React fetch method from jQuery in home.js, to catch Medium article, please help me, thank you.

**Comment by masquel** [comment]
Hey, what do you need exactly? Using jquery with react is not a best way.

**Comment by bluetch** [comment]
Hi @masquel , Yes, I would like to no use jQuery, but I don't familiar with react yet, so that why I am requesting about

**Comment by bluetch** [comment]
Hi @masquel , it works, thank you. Although I don't know wrong with last night ...
