### ISSUE TITLE
webpack implement

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee.design#3]
Excuse me, I would like to implement webpack to current website, but it too hard to React beginner, anybody could help me?

**Comment by gmlnchv** [comment]
Why? This seems to be a `create-react-app` where the Webpack configuration is hidden from you unless you [eject](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject).

**Comment by bluetch** [comment]
Hi @gmlnchv , I was try to install some node-module, but lots of tutorial is about webpack style, like react-ga, I don't know how to implement this kind of module ..

https://github.com/react-ga/react-ga

**Comment by gmlnchv** [comment]
You don't need to do anything with Webpack for that. Have a look at the docs here - https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#installing-a-dependency

**Comment by ad-dan** [comment]
@gmlnchv 's advice is correct. `create-react-app` is the best approach for a beginner to react. Just use it and install packages like how you would normally do (`npm install --save foo`)

**Comment by bluetch** [comment]
Got it, thank you @gmlnchv and @ad-dan , I will keep trying.
